# Problem 12 : Highly divisible triangular number
# The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 

# The first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# Let us list the factors of the first seven triangle numbers:
#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28

# We can see that 28 is the first triangle number to have over five divisors.
# What is the value of the first triangle number to have over five hundred divisors?


# 問題 12 : 高度分割可能三角数
# 三角数の数列は自然数を足し合わせることで生成される．
# 例えば，3番目の三角数は1 + 2 + 3 + 4 + 5 + 6 + 7 = 28である．

# はじめの10個は以下のようになっている．
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# はじめの7個の三角数の公約数は以下のようになる．
#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28

# 上のリストからわかるように，7番目の三角数ではじめて公約数が5つとなる．
# 500個の公約数が出るはじめの三角数はいくつか．

